# Generated by Django 4.2.6 on 2023-10-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('I', 'In store'), ('N', 'New order')], default='I', max_length=1),
        ),
    ]
