# Generated by Django 4.2.6 on 2023-10-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_remove_product_type_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('left_side_image', models.ImageField(upload_to='')),
                ('right_side_image', models.ImageField(upload_to='')),
                ('front_image', models.ImageField(upload_to='')),
                ('rear_image', models.ImageField(upload_to='')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.customer')),
            ],
        ),
    ]
