# Generated by Django 4.2.6 on 2023-10-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.product'),
        ),
        migrations.AlterField(
            model_name='wishlistitems',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistitems', to='Store.wishlist'),
        ),
    ]
